// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

public partial class Certificate
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("id")]
    [StringLength(7)]
    [Unicode(false)]
    public string Id { get; set; }

    [Column("comptype")]
    [StringLength(2)]
    [Unicode(false)]
    public string Comptype { get; set; }

    [Column("compseq")]
    [StringLength(5)]
    [Unicode(false)]
    public string Compseq { get; set; }

    [Column("certdate", TypeName = "datetime")]
    public DateTime? Certdate { get; set; }

    [Column("cert")]
    [StringLength(16)]
    [Unicode(false)]
    public string Cert { get; set; }

    [Column("userid")]
    [StringLength(16)]
    [Unicode(false)]
    public string Userid { get; set; }

    [Column("certfile")]
    [StringLength(255)]
    [Unicode(false)]
    public string Certfile { get; set; }

    [Column("jur")]
    [StringLength(255)]
    [Unicode(false)]
    public string Jur { get; set; }

    [Column("pmtid")]
    public int? Pmtid { get; set; }

    [Column("dsbid")]
    public int? Dsbid { get; set; }

    [Column("transid")]
    [StringLength(10)]
    [Unicode(false)]
    public string Transid { get; set; }

    [Column("authcode")]
    [StringLength(10)]
    [Unicode(false)]
    public string Authcode { get; set; }

    [Column("complete")]
    public bool Complete { get; set; }

    [Column("networkaddress")]
    [StringLength(50)]
    [Unicode(false)]
    public string Networkaddress { get; set; }
}