// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

public partial class Certtype
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("cert")]
    [StringLength(15)]
    [Unicode(false)]
    public string Cert { get; set; }

    [Column("description")]
    [StringLength(100)]
    [Unicode(false)]
    public string Description { get; set; }
}