// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Index("Id", "Comptype", "Compseq", Name = "idx")]
public partial class Change
{
    [Key]
    [Column("idctr")]
    public int Idctr { get; set; }

    [Column("id")]
    [StringLength(9)]
    [Unicode(false)]
    public string Id { get; set; }

    [Column("comptype")]
    [StringLength(2)]
    [Unicode(false)]
    public string Comptype { get; set; }

    [Column("compseq")]
    [StringLength(5)]
    [Unicode(false)]
    public string Compseq { get; set; }

    [Column("userid")]
    [StringLength(20)]
    [Unicode(false)]
    public string Userid { get; set; }

    [Column("datafield")]
    [StringLength(20)]
    [Unicode(false)]
    public string Datafield { get; set; }

    [Column("olddata")]
    [StringLength(50)]
    [Unicode(false)]
    public string Olddata { get; set; }

    [Column("newdata")]
    [StringLength(50)]
    [Unicode(false)]
    public string Newdata { get; set; }

    [Column("chdate", TypeName = "datetime")]
    public DateTime? Chdate { get; set; }
}