// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Keyless]
[Table("countrycodes")]
public partial class Countrycode
{
    [Column("country")]
    [StringLength(255)]
    public string Country { get; set; }

    [Required]
    [Column("countrycode")]
    [StringLength(3)]
    public string Countrycode1 { get; set; }
}