// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("County")]
public partial class County
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("code")]
    [StringLength(3)]
    public string Code { get; set; }

    [Column("county")]
    [StringLength(50)]
    public string County1 { get; set; }
}