// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("Country")]
public partial class Country
{
    [Key]
    [StringLength(3)]
    public string Code { get; set; }

    [Column("Country")]
    [StringLength(255)]
    public string Country1 { get; set; }
}