// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("emailaddress")]
[Index("Id", "Comptype", "Compseq", Name = "IX_compid")]
[Index("Emailaddress1", Name = "IX_emailaddress")]
public partial class Emailaddress
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("id")]
    [StringLength(7)]
    [Unicode(false)]
    public string Id { get; set; }

    [Column("comptype")]
    [StringLength(2)]
    [Unicode(false)]
    public string Comptype { get; set; }

    [Column("compseq")]
    [StringLength(5)]
    [Unicode(false)]
    public string Compseq { get; set; }

    [Column("status")]
    [StringLength(1)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column("dateadded", TypeName = "datetime")]
    public DateTime? Dateadded { get; set; }

    [Column("useridadded")]
    [StringLength(50)]
    [Unicode(false)]
    public string Useridadded { get; set; }

    [Column("datestatuschanged", TypeName = "datetime")]
    public DateTime? Datestatuschanged { get; set; }

    [Column("useridstatuschanged")]
    [StringLength(50)]
    [Unicode(false)]
    public string Useridstatuschanged { get; set; }

    [Column("emailaddress")]
    [StringLength(255)]
    public string Emailaddress1 { get; set; }

    [Column("sent")]
    public int? Sent { get; set; }

    [Column("notsent")]
    public int? Notsent { get; set; }

    [Column("datenotsent", TypeName = "datetime")]
    public DateTime? Datenotsent { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ChgDateViaTrigger { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateAddedViaTrigger { get; set; }
}