// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("ERSManageQ")]
public partial class ErsmanageQ
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("code")]
    [StringLength(3)]
    [Unicode(false)]
    public string Code { get; set; }

    [Column("CBI")]
    [StringLength(10)]
    [Unicode(false)]
    public string Cbi { get; set; }

    [Column("ID")]
    [StringLength(7)]
    [Unicode(false)]
    public string Id { get; set; }

    [Column("comptype")]
    [StringLength(2)]
    [Unicode(false)]
    public string Comptype { get; set; }

    [Column("compseq")]
    [StringLength(5)]
    [Unicode(false)]
    public string Compseq { get; set; }

    [Column("xml")]
    public string Xml { get; set; }

    [Column("dateadded", TypeName = "datetime")]
    public DateTime? Dateadded { get; set; }

    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("doc")]
    [StringLength(255)]
    public string Doc { get; set; }

    [Column("ersID")]
    [StringLength(12)]
    public string ErsId { get; set; }

    [Column("status")]
    [StringLength(1)]
    [Unicode(false)]
    public string Status { get; set; }
}