// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("ERSQueue")]
[Index("Ctr", "Qtype", Name = "IX_ERSQueue", IsDescending = new[] { true, false })]
public partial class Ersqueue
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("id")]
    [StringLength(7)]
    [Unicode(false)]
    public string Id { get; set; }

    [Column("comptype")]
    [StringLength(2)]
    [Unicode(false)]
    public string Comptype { get; set; }

    [Column("compseq")]
    [StringLength(5)]
    [Unicode(false)]
    public string Compseq { get; set; }

    [Column("retries")]
    public int? Retries { get; set; }

    [Column("response")]
    public string Response { get; set; }

    [Column("queuetime", TypeName = "datetime")]
    public DateTime? Queuetime { get; set; }

    [Column("qtype")]
    [StringLength(1)]
    [Unicode(false)]
    public string Qtype { get; set; }

    [Column("source")]
    [StringLength(1)]
    [Unicode(false)]
    public string Source { get; set; }

    [Column("ersid")]
    [StringLength(12)]
    [Unicode(false)]
    public string Ersid { get; set; }
}