// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Index("Userid", Name = "Userid")]
public partial class Fee
{
    [Key]
    [Column("type")]
    [StringLength(4)]
    [Unicode(false)]
    public string Type { get; set; }

    [Column("Desc_")]
    [StringLength(30)]
    [Unicode(false)]
    public string Desc { get; set; }

    [Column("amount", TypeName = "money")]
    public decimal? Amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Processdate { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Userid { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Acctnum { get; set; }

    [Column("LLCFee")]
    public int? Llcfee { get; set; }

    [Column("KRS")]
    [StringLength(50)]
    [Unicode(false)]
    public string Krs { get; set; }
}