// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("filmcodes")]
public partial class Filmcode
{
    [Key]
    [Column("doctype")]
    [StringLength(3)]
    [Unicode(false)]
    public string Doctype { get; set; }

    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("shortname")]
    [StringLength(15)]
    [Unicode(false)]
    public string Shortname { get; set; }
}