// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("FutureAct")]
[Index("Mscompid", "Mscomptyp", "Mscompseq", Name = "FACT_msidx")]
[Index("Id", "Comptyp", "Compseq", Name = "FAct_idx")]
[Index("Code", Name = "code")]
public partial class FutureAct
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("id")]
    [StringLength(7)]
    [Unicode(false)]
    public string Id { get; set; }

    [Column("comptyp")]
    [StringLength(2)]
    [Unicode(false)]
    public string Comptyp { get; set; }

    [Column("compseq")]
    [StringLength(5)]
    [Unicode(false)]
    public string Compseq { get; set; }

    [Column("datetime")]
    [StringLength(50)]
    [Unicode(false)]
    public string Datetime { get; set; }

    [Column("code")]
    [StringLength(3)]
    [Unicode(false)]
    public string Code { get; set; }

    [Column("subcode")]
    [StringLength(2)]
    [Unicode(false)]
    public string Subcode { get; set; }

    [Column("mscomptyp")]
    [StringLength(2)]
    [Unicode(false)]
    public string Mscomptyp { get; set; }

    [Column("mscompid")]
    [StringLength(7)]
    [Unicode(false)]
    public string Mscompid { get; set; }

    [Column("mscompseq")]
    [StringLength(5)]
    [Unicode(false)]
    public string Mscompseq { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EffDate { get; set; }

    [Column("userid")]
    [StringLength(16)]
    [Unicode(false)]
    public string Userid { get; set; }

    [Column("dt", TypeName = "datetime")]
    public DateTime? Dt { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Text { get; set; }

    [Column("nqname")]
    [StringLength(140)]
    [Unicode(false)]
    public string Nqname { get; set; }

    [Column(TypeName = "money")]
    public decimal? Fee { get; set; }
}