// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Keyless]
[Table("FutureProcessed")]
public partial class FutureProcessed
{
    [Column("ctr")]
    public int? Ctr { get; set; }

    [Column("id")]
    [StringLength(7)]
    public string Id { get; set; }

    [Column("comptype")]
    [StringLength(2)]
    public string Comptype { get; set; }

    [Column("compseq")]
    [StringLength(5)]
    public string Compseq { get; set; }

    [Column("code")]
    [StringLength(8)]
    public string Code { get; set; }
}