// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("NewArponline")]
[Index("Id", "Comptype", "Compseq", Name = "IX_CompanyID")]
public partial class NewArponline
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("id")]
    [StringLength(7)]
    [Unicode(false)]
    public string Id { get; set; }

    [Column("comptype")]
    [StringLength(2)]
    [Unicode(false)]
    public string Comptype { get; set; }

    [Column("compseq")]
    [StringLength(5)]
    [Unicode(false)]
    public string Compseq { get; set; }

    [Column("arpdate", TypeName = "datetime")]
    public DateTime? Arpdate { get; set; }

    [Column("poaddr1")]
    [StringLength(255)]
    [Unicode(false)]
    public string Poaddr1 { get; set; }

    [Column("poaddr2")]
    [StringLength(50)]
    [Unicode(false)]
    public string Poaddr2 { get; set; }

    [Column("poaddr3")]
    [StringLength(50)]
    [Unicode(false)]
    public string Poaddr3 { get; set; }

    [Column("poaddr4")]
    [StringLength(50)]
    [Unicode(false)]
    public string Poaddr4 { get; set; }

    [Column("pocity")]
    [StringLength(50)]
    [Unicode(false)]
    public string Pocity { get; set; }

    [Column("postate")]
    [StringLength(2)]
    [Unicode(false)]
    public string Postate { get; set; }

    [Column("pozip")]
    [StringLength(10)]
    [Unicode(false)]
    public string Pozip { get; set; }

    [Column("raaddr1")]
    [StringLength(255)]
    [Unicode(false)]
    public string Raaddr1 { get; set; }

    [Column("raaddr2")]
    [StringLength(50)]
    [Unicode(false)]
    public string Raaddr2 { get; set; }

    [Column("raaddr3")]
    [StringLength(50)]
    [Unicode(false)]
    public string Raaddr3 { get; set; }

    [Column("raaddr4")]
    [StringLength(50)]
    [Unicode(false)]
    public string Raaddr4 { get; set; }

    [Column("racity")]
    [StringLength(50)]
    [Unicode(false)]
    public string Racity { get; set; }

    [Column("rastate")]
    [StringLength(2)]
    [Unicode(false)]
    public string Rastate { get; set; }

    [Column("razip")]
    [StringLength(10)]
    [Unicode(false)]
    public string Razip { get; set; }

    [Column("raname")]
    [StringLength(255)]
    [Unicode(false)]
    public string Raname { get; set; }

    [Column("fee", TypeName = "money")]
    public decimal? Fee { get; set; }

    [Column("signature")]
    [StringLength(120)]
    [Unicode(false)]
    public string Signature { get; set; }

    [Column("title")]
    [StringLength(140)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column("pressignature")]
    [StringLength(120)]
    [Unicode(false)]
    public string Pressignature { get; set; }

    [Column("pmtid")]
    public int? Pmtid { get; set; }

    [Column("disbid")]
    public int? Disbid { get; set; }

    [Column("transid")]
    [StringLength(10)]
    [Unicode(false)]
    public string Transid { get; set; }

    [Column("managedby")]
    [StringLength(1)]
    [Unicode(false)]
    public string Managedby { get; set; }

    [Column("completed")]
    public bool? Completed { get; set; }

    [Column("authcode")]
    [StringLength(10)]
    [Unicode(false)]
    public string Authcode { get; set; }

    [Column("feetype")]
    [StringLength(4)]
    [Unicode(false)]
    public string Feetype { get; set; }

    [Column("printed")]
    public bool? Printed { get; set; }

    [Column("fileyear")]
    [StringLength(4)]
    [Unicode(false)]
    public string Fileyear { get; set; }

    [Column("coop")]
    public bool? Coop { get; set; }

    [Column("datecreated", TypeName = "datetime")]
    public DateTime? Datecreated { get; set; }

    [Column("datelastread", TypeName = "datetime")]
    public DateTime? Datelastread { get; set; }

    [Column("dateupdated", TypeName = "datetime")]
    public DateTime? Dateupdated { get; set; }

    [Column("coop279")]
    public bool? Coop279 { get; set; }

    [Column("amendment")]
    public bool? Amendment { get; set; }

    [Column("email")]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }
}