// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

public partial class NewArpOfficerChange
{
    [Column("ctr")]
    public int? Ctr { get; set; }

    [Column("arpctr")]
    public int? Arpctr { get; set; }

    [Column("newoffice")]
    [StringLength(1)]
    [Unicode(false)]
    public string Newoffice { get; set; }

    [Column("newfname")]
    [StringLength(20)]
    [Unicode(false)]
    public string Newfname { get; set; }

    [Column("newmname")]
    [StringLength(20)]
    [Unicode(false)]
    public string Newmname { get; set; }

    [Column("newlname")]
    [StringLength(255)]
    [Unicode(false)]
    public string Newlname { get; set; }

    [Column("newaddr")]
    [StringLength(255)]
    [Unicode(false)]
    public string Newaddr { get; set; }

    [Column("oldoffice")]
    [StringLength(1)]
    [Unicode(false)]
    public string Oldoffice { get; set; }

    [Column("oldfname")]
    [StringLength(20)]
    [Unicode(false)]
    public string Oldfname { get; set; }

    [Column("oldmname")]
    [StringLength(20)]
    [Unicode(false)]
    public string Oldmname { get; set; }

    [Column("oldlname")]
    [StringLength(255)]
    [Unicode(false)]
    public string Oldlname { get; set; }

    [Column("oldaddr")]
    [StringLength(255)]
    [Unicode(false)]
    public string Oldaddr { get; set; }

    [Column("chgdate", TypeName = "datetime")]
    public DateTime? Chgdate { get; set; }

    [Key]
    [Column("ID")]
    public int Id { get; set; }
}