// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("NextID")]
public partial class NextId
{
    [Required]
    [Column("NextID")]
    [StringLength(7)]
    [Unicode(false)]
    public string NextId1 { get; set; }

    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }
}