// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Index("Office", Name = "Office")]
[Index("Chgdate", Name = "officers_chgdatex")]
[Index("Lname", "Fname", "Mname", Name = "officers_namex")]
[Index("Office", "Lname", Name = "officers_office_lname")]
public partial class Officer
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("id")]
    [StringLength(7)]
    [Unicode(false)]
    public string Id { get; set; }

    [Column("comptype")]
    [StringLength(2)]
    [Unicode(false)]
    public string Comptype { get; set; }

    [Column("compseq")]
    [StringLength(5)]
    [Unicode(false)]
    public string Compseq { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Office { get; set; }

    [Column("FName")]
    [StringLength(20)]
    [Unicode(false)]
    public string Fname { get; set; }

    [Column("MName")]
    [StringLength(20)]
    [Unicode(false)]
    public string Mname { get; set; }

    [Column("olname")]
    [StringLength(20)]
    [Unicode(false)]
    public string Olname { get; set; }

    [Column("chgdate", TypeName = "datetime")]
    public DateTime? Chgdate { get; set; }

    [Column("lname")]
    [StringLength(255)]
    [Unicode(false)]
    public string Lname { get; set; }

    [Column("address")]
    [StringLength(255)]
    [Unicode(false)]
    public string Address { get; set; }

    [Column("addr1")]
    [StringLength(255)]
    [Unicode(false)]
    public string Addr1 { get; set; }

    [Column("addr2")]
    [StringLength(255)]
    [Unicode(false)]
    public string Addr2 { get; set; }

    [Column("addr3")]
    [StringLength(255)]
    [Unicode(false)]
    public string Addr3 { get; set; }

    [Column("city")]
    [StringLength(255)]
    [Unicode(false)]
    public string City { get; set; }

    [Column("state")]
    [StringLength(255)]
    [Unicode(false)]
    public string State { get; set; }

    [Column("zip")]
    [StringLength(255)]
    [Unicode(false)]
    public string Zip { get; set; }

    [Column("country")]
    [StringLength(255)]
    [Unicode(false)]
    public string Country { get; set; }

    [Column("oname")]
    [StringLength(255)]
    [Unicode(false)]
    public string Oname { get; set; }
}