// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Index("Office", Name = "IX_Offtypes", IsUnique = true)]
public partial class Offtype
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("office")]
    [StringLength(1)]
    [Unicode(false)]
    public string Office { get; set; }

    [Column("title")]
    [StringLength(20)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column("offorder")]
    public int? Offorder { get; set; }

    [Column("iacatitle")]
    [StringLength(50)]
    [Unicode(false)]
    public string Iacatitle { get; set; }
}