// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Keyless]
public partial class OnlineFiling
{
    [Column("OnlineFilingID")]
    public int OnlineFilingId { get; set; }

    [Column("CartID")]
    [StringLength(64)]
    public string CartId { get; set; }

    [StringLength(50)]
    public string LocalReference { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? FeeAmount { get; set; }

    [StringLength(10)]
    public string FeeType { get; set; }

    [Column("LLAAmendmentAdopted")]
    public bool? LlaamendmentAdopted { get; set; }
}