// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Index("Userid", Name = "idx_Payments_userid_Amount")]
[Index("Checknum", Name = "payments_checknumx")]
[Index("Paydate", Name = "payments_paydatex")]
[Index("PayinVoucher", Name = "payments_pivx")]
public partial class Payment
{
    [Column("paydate", TypeName = "datetime")]
    public DateTime? Paydate { get; set; }

    [Column("id")]
    [StringLength(7)]
    [Unicode(false)]
    public string Id { get; set; }

    [Column("comptyp")]
    [StringLength(2)]
    [Unicode(false)]
    public string Comptyp { get; set; }

    [Column("compseq")]
    [StringLength(5)]
    [Unicode(false)]
    public string Compseq { get; set; }

    [Column("type")]
    [StringLength(2)]
    [Unicode(false)]
    public string Type { get; set; }

    [Column("feetype")]
    [StringLength(4)]
    [Unicode(false)]
    public string Feetype { get; set; }

    [Column("checknum")]
    [StringLength(40)]
    [Unicode(false)]
    public string Checknum { get; set; }

    [Column("amount", TypeName = "money")]
    public decimal? Amount { get; set; }

    [Column("status")]
    [StringLength(1)]
    [Unicode(false)]
    public string Status { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string PayinVoucher { get; set; }

    public short? PayinCount { get; set; }

    [Column("userid")]
    [StringLength(10)]
    [Unicode(false)]
    public string Userid { get; set; }

    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("reason")]
    [StringLength(255)]
    [Unicode(false)]
    public string Reason { get; set; }
}