// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Index("Name", Name = "Name")]
public partial class Person
{
    /// <summary>
    /// ID of the company record this name refers to
    /// </summary>
    [Column("CompanyID")]
    [StringLength(7)]
    [Unicode(false)]
    public string CompanyId { get; set; }

    /// <summary>
    /// No longer used (deprecated)
    /// </summary>
    [StringLength(1)]
    [Unicode(false)]
    public string Seq { get; set; }

    /// <summary>
    /// Officer type of this name (from offtypes table)
    /// </summary>
    [StringLength(1)]
    [Unicode(false)]
    public string Type { get; set; }

    /// <summary>
    /// The name of the person or entity
    /// </summary>
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    /// <summary>
    /// A unique idientifier for this record (autonumber)
    /// </summary>
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("prefix")]
    [StringLength(255)]
    public string Prefix { get; set; }

    [Column("fname")]
    [StringLength(255)]
    public string Fname { get; set; }

    [Column("mname")]
    [StringLength(255)]
    public string Mname { get; set; }

    [Column("lname")]
    [StringLength(255)]
    public string Lname { get; set; }

    [Column("suffix")]
    [StringLength(255)]
    public string Suffix { get; set; }

    [Column("oname")]
    [StringLength(255)]
    public string Oname { get; set; }

    [Column("addr1")]
    [StringLength(255)]
    public string Addr1 { get; set; }

    [Column("addr2")]
    [StringLength(255)]
    public string Addr2 { get; set; }

    [Column("addr3")]
    [StringLength(255)]
    public string Addr3 { get; set; }

    [Column("city")]
    [StringLength(255)]
    public string City { get; set; }

    [Column("state")]
    [StringLength(2)]
    public string State { get; set; }

    [Column("zip")]
    [StringLength(20)]
    public string Zip { get; set; }

    [Column("country")]
    [StringLength(3)]
    public string Country { get; set; }
}