// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("RACPOCReturn")]
[Index("Id", "Comptype", "Compseq", Name = "IX_RACPOCID")]
public partial class Racpocreturn
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("ID")]
    [StringLength(7)]
    [Unicode(false)]
    public string Id { get; set; }

    [Column("comptype")]
    [StringLength(2)]
    [Unicode(false)]
    public string Comptype { get; set; }

    [Column("compseq")]
    [StringLength(5)]
    [Unicode(false)]
    public string Compseq { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RecipientName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MailAddress1 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MailAddress2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MailAddress3 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateMailed { get; set; }

    [Column("userid")]
    [StringLength(22)]
    [Unicode(false)]
    public string Userid { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MailAddress4 { get; set; }

    [Column("entityname")]
    public bool? Entityname { get; set; }

    [Column("notcurrra")]
    public bool? Notcurrra { get; set; }

    [Column("notcurpo")]
    public bool? Notcurpo { get; set; }

    [Column("poaddrinc")]
    public bool? Poaddrinc { get; set; }

    [Column("mustbesign")]
    public bool? Mustbesign { get; set; }

    [Column("nofee")]
    public bool? Nofee { get; set; }

    [Column("nochangepo")]
    public bool? Nochangepo { get; set; }

    [Column("nochangera")]
    public bool? Nochangera { get; set; }

    [Column("feenonprof")]
    public bool? Feenonprof { get; set; }

    [Column("feeprof")]
    public bool? Feeprof { get; set; }

    [Column("notsigned")]
    public bool? Notsigned { get; set; }

    [Column("arpaddfee")]
    public bool? Arpaddfee { get; set; }

    [Column("notgoodstanding")]
    public bool? Notgoodstanding { get; set; }

    [Column("checknum")]
    [StringLength(16)]
    [Unicode(false)]
    public string Checknum { get; set; }

    [Column("checkamt", TypeName = "money")]
    public decimal? Checkamt { get; set; }

    [Column("noconsent")]
    public bool? Noconsent { get; set; }

    [Column("addrbad")]
    public bool? Addrbad { get; set; }

    [Column("notcurraaddr")]
    public bool? Notcurraaddr { get; set; }

    [Column("notownra")]
    public bool? Notownra { get; set; }

    [Column("other")]
    [StringLength(2048)]
    [Unicode(false)]
    public string Other { get; set; }

    [Column("addfee", TypeName = "money")]
    public decimal? Addfee { get; set; }

    [Column("image")]
    [StringLength(255)]
    [Unicode(false)]
    public string Image { get; set; }

    [Column("totalamt", TypeName = "money")]
    public decimal? Totalamt { get; set; }

    [Column("dissolved")]
    public bool? Dissolved { get; set; }
}