// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("returnletterlinks")]
public partial class Returnletterlink
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("returnletterid")]
    public int Returnletterid { get; set; }

    [Column("panel")]
    [StringLength(24)]
    [Unicode(false)]
    public string Panel { get; set; }

    [Column("textid")]
    public int Textid { get; set; }
}