// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("Searchlog")]
[Index("Qdate", Name = "'poopie'")]
public partial class Searchlog
{
    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("id")]
    public int? Id { get; set; }

    [Column("app")]
    [StringLength(50)]
    [Unicode(false)]
    public string App { get; set; }

    [Column("query")]
    [StringLength(255)]
    [Unicode(false)]
    public string Query { get; set; }

    [Column("qdate", TypeName = "datetime")]
    public DateTime? Qdate { get; set; }

    [Column("rescnt")]
    public int? Rescnt { get; set; }

    [Column("loc")]
    [StringLength(50)]
    [Unicode(false)]
    public string Loc { get; set; }
}