// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntitySrvr.Models;

[Table("XStatus")]
public partial class Xstatus
{
    [Column("ID")]
    [StringLength(7)]
    [Unicode(false)]
    public string Id { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string Comptype { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Compseq { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Standing { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Status { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Country { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string State { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string Type { get; set; }

    [Column("RAname")]
    [StringLength(255)]
    [Unicode(false)]
    public string Raname { get; set; }

    [Column("RAaddr1")]
    [StringLength(255)]
    [Unicode(false)]
    public string Raaddr1 { get; set; }

    [Column("RAaddr2")]
    [StringLength(50)]
    [Unicode(false)]
    public string Raaddr2 { get; set; }

    [Column("RAaddr3")]
    [StringLength(50)]
    [Unicode(false)]
    public string Raaddr3 { get; set; }

    [Column("RAaddr4")]
    [StringLength(50)]
    [Unicode(false)]
    public string Raaddr4 { get; set; }

    [Column("RAcity")]
    [StringLength(32)]
    [Unicode(false)]
    public string Racity { get; set; }

    [Column("RAstate")]
    [StringLength(2)]
    [Unicode(false)]
    public string Rastate { get; set; }

    [Column("RAzip")]
    [StringLength(10)]
    [Unicode(false)]
    public string Razip { get; set; }

    [Column("POAddr1")]
    [StringLength(255)]
    [Unicode(false)]
    public string Poaddr1 { get; set; }

    [Column("POAddr2")]
    [StringLength(50)]
    [Unicode(false)]
    public string Poaddr2 { get; set; }

    [Column("POAddr3")]
    [StringLength(50)]
    [Unicode(false)]
    public string Poaddr3 { get; set; }

    [Column("POAddr4")]
    [StringLength(50)]
    [Unicode(false)]
    public string Poaddr4 { get; set; }

    [Column("POCity")]
    [StringLength(32)]
    [Unicode(false)]
    public string Pocity { get; set; }

    [Column("POState")]
    [StringLength(2)]
    [Unicode(false)]
    public string Postate { get; set; }

    [Column("POZip")]
    [StringLength(10)]
    [Unicode(false)]
    public string Pozip { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Filedate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Orgdate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Authdate { get; set; }

    [StringLength(4)]
    [Unicode(false)]
    public string Numofcr { get; set; }

    [Column("numofshr")]
    [StringLength(10)]
    [Unicode(false)]
    public string Numofshr { get; set; }

    [Column("raresdte", TypeName = "datetime")]
    public DateTime? Raresdte { get; set; }

    [Column("expdte", TypeName = "datetime")]
    public DateTime? Expdte { get; set; }

    [Column("mangnum")]
    [StringLength(1)]
    [Unicode(false)]
    public string Mangnum { get; set; }

    [Column("rendte", TypeName = "datetime")]
    public DateTime? Rendte { get; set; }

    [Column("applname")]
    [StringLength(50)]
    [Unicode(false)]
    public string Applname { get; set; }

    [Column("appltitl")]
    [StringLength(50)]
    [Unicode(false)]
    public string Appltitl { get; set; }

    [Column("lastrdte", TypeName = "datetime")]
    public DateTime? Lastrdte { get; set; }

    [Column("prevrdte", TypeName = "datetime")]
    public DateTime? Prevrdte { get; set; }

    [Column("parpre")]
    [StringLength(10)]
    [Unicode(false)]
    public string Parpre { get; set; }

    [Column("parcomno")]
    [StringLength(10)]
    [Unicode(false)]
    public string Parcomno { get; set; }

    [Column("parcom")]
    [StringLength(10)]
    [Unicode(false)]
    public string Parcom { get; set; }

    [Column("parpreno")]
    [StringLength(10)]
    [Unicode(false)]
    public string Parpreno { get; set; }

    [Column("nameindex")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nameindex { get; set; }

    [Column("profit")]
    [StringLength(1)]
    [Unicode(false)]
    public string Profit { get; set; }

    [Column("docloc")]
    [StringLength(8)]
    [Unicode(false)]
    public string Docloc { get; set; }

    [Column("recorddate", TypeName = "datetime")]
    public DateTime? Recorddate { get; set; }

    [Key]
    [Column("ctr")]
    public int Ctr { get; set; }

    [Column("chgdate", TypeName = "datetime")]
    public DateTime? Chgdate { get; set; }

    [Column("FEIN")]
    [StringLength(1000)]
    [Unicode(false)]
    public string Fein { get; set; }

    [Column("termdate", TypeName = "datetime")]
    public DateTime? Termdate { get; set; }

    [Column("arppin")]
    [StringLength(4)]
    [Unicode(false)]
    public string Arppin { get; set; }

    [Column("krs277date", TypeName = "datetime")]
    public DateTime? Krs277date { get; set; }

    [Column("printed")]
    public bool? Printed { get; set; }

    [Column("longform", TypeName = "text")]
    public string Longform { get; set; }

    [Column("coop")]
    public bool? Coop { get; set; }

    [Column("dontchange")]
    public bool? Dontchange { get; set; }

    [Column("coop279")]
    public bool? Coop279 { get; set; }

    [Column("KyGovXML")]
    [Unicode(false)]
    public string KyGovXml { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string Purpose { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string FilerName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string FilerAddr1 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FilerAddr2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FilerAddr3 { get; set; }

    [StringLength(32)]
    [Unicode(false)]
    public string FilerCity { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string FilerState { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string FilerZip { get; set; }

    /// <summary>
    /// userid of original filer
    /// </summary>
    [Column("userid")]
    [StringLength(50)]
    [Unicode(false)]
    public string Userid { get; set; }

    /// <summary>
    /// Eemail address for annual report notification.
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string EmailAddress { get; set; }

    [Column("KyGovID")]
    public int? KyGovId { get; set; }

    public bool? Arpprinted { get; set; }

    [Column("CBI")]
    [StringLength(10)]
    public string Cbi { get; set; }

    [Column("RAprefix")]
    [StringLength(255)]
    public string Raprefix { get; set; }

    [Column("RAfname")]
    [StringLength(255)]
    public string Rafname { get; set; }

    [Column("RAmname")]
    [StringLength(255)]
    public string Ramname { get; set; }

    [Column("RAlname")]
    [StringLength(255)]
    public string Ralname { get; set; }

    [Column("RAsuffix")]
    [StringLength(255)]
    public string Rasuffix { get; set; }

    [Column("RAoname")]
    [StringLength(255)]
    public string Raoname { get; set; }

    [Column("ERSCountry")]
    [StringLength(3)]
    public string Erscountry { get; set; }

    [StringLength(100)]
    public string FilerEmail { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FilerPhone { get; set; }

    [Column("LLLP")]
    public bool? Lllp { get; set; }

    [Column("PLLC")]
    public bool? Pllc { get; set; }

    public bool? SeriesTrust { get; set; }

    [Column("NCR")]
    [StringLength(255)]
    public string Ncr { get; set; }

    [Column("POCountry")]
    [StringLength(3)]
    public string Pocountry { get; set; }

    [Column("ranameremoved")]
    public bool? Ranameremoved { get; set; }

    [Column("raaddrremoved")]
    public bool? Raaddrremoved { get; set; }

    [Column("CBILetterSent", TypeName = "datetime")]
    public DateTime? CbiletterSent { get; set; }

    [Column("benefit")]
    public bool? Benefit { get; set; }

    [Column("veteranowned")]
    public bool? Veteranowned { get; set; }

    [Column("cantupdateonline")]
    public bool? Cantupdateonline { get; set; }

    [Column("interrogatory")]
    public bool? Interrogatory { get; set; }

    [Column("RAEntitysig")]
    [StringLength(255)]
    public string Raentitysig { get; set; }
}